name = "JustinWillmert"
uuid = "b03618a4-f3f8-577f-b15b-d9c21dacf23e"
repo = "https://github.com/jmert/Registry.jl"

description = """
Repository of Justin Willmert's julia packages.
"""

[packages]
2119f1ac-fb78-50f5-8cc0-dda848ebdb19 = { name = "AssociatedLegendrePolynomials", path = "A/AssociatedLegendrePolynomials" }
592991c5-7c29-5f04-aea2-6d9f924ef2a1 = { name = "CMB", path = "C/CMB" }
674b2976-56af-439b-a2b1-837be4a3d087 = { name = "UnixMmap", path = "U/UnixMmap" }
7642852e-7f09-11e9-134e-0940411082b6 = { name = "Legendre", path = "L/Legendre" }
d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35 = { name = "BitFlags", path = "B/BitFlags" }
